baseurl = "/"
languageCode = "en-us"
title = "Homepage"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

[languages]
  
  [languages.en]
    languageName = "en"
    contentDir = "content/en"
    

  [languages.ro]
    languageName = "ro"
    contentDir = "content/ro"